update readme
imagekit-developer/imagekit-java pull request #33
Opened 2024-05-10 10:01 UTC by ankur-dwivedi

2024-05-10 11:28 UTC, ahnv requested changes

2024-05-10 11:28 UTC, ahnv commented on README.md
> +tags[2] = "Engineer";
Where are these being used?

2024-05-10 11:31 UTC, ankur-dwivedi commented on README.md
> +tags[2] = "Engineer";
ha removed it was not needed

2024-05-13 05:10 UTC, ahnv approved these changes

2024-05-13 07:30 UTC, merged